@SuppliersAPI_HostAddress = http://localhost:5010

GET {{SuppliersAPI_HostAddress}}/weatherforecast/
Accept: application/json

### ExampleExcel Report
POST {{SuppliersAPI_HostAddress}}/Report/ExampleExcel/
Content-Type: application/json

{
}
###

### ContpaqExcel Report - Sin filtros
POST {{SuppliersAPI_HostAddress}}/Report/ContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "",
  "FechaFinal": "",
  "TipoComprobante": null,
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###

### ContpaqExcel Report - Con filtros
# TipoComprobante: "I" = Ingreso, "E" = Egreso, "T" = Traslado, "N" = Nómina, "P" = Pago
POST {{SuppliersAPI_HostAddress}}/Report/ContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "01/01/2024",
  "FechaFinal": "31/12/2024",
  "TipoComprobante": "I",
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###

### Recibidas CONTPAQ Report - Sin filtros
POST {{SuppliersAPI_HostAddress}}/Report/RecibidasContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "",
  "FechaFinal": "",
  "TipoComprobante": null,
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###

### Recibidas CONTPAQ Report - Con filtros
POST {{SuppliersAPI_HostAddress}}/Report/RecibidasContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "01/01/2024",
  "FechaFinal": "31/12/2024",
  "TipoComprobante": "I",
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###

### Emitidas CONTPAQ Report - Sin filtros
POST {{SuppliersAPI_HostAddress}}/Report/EmitidasContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "",
  "FechaFinal": "",
  "TipoComprobante": null,
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###

### Emitidas CONTPAQ Report - Con filtros
POST {{SuppliersAPI_HostAddress}}/Report/EmitidasContpaqExcel/
Content-Type: application/json

{
  "FolioFiscal": "",
  "FechaInicial": "01/01/2024",
  "FechaFinal": "31/12/2024",
  "TipoComprobante": "I",
  "Rfc": "",
  "Serie": "",
  "Folio": "",
  "Download": true
}
###
